

#generated IATA city codes

iata_codes={'agartala': ('ixa',
  'agartala airport singerbhil airport agartala air force station'),
 'agatti': ('agx', 'agatti aerodrome'),
 'agra': ('agr', 'kheria airport / (agra air force station)'),
 'aizawl': ('ajl', 'turial air base'),
 'akola': ('akd', 'akola airport'),
 'allahabad': ('ixd', 'allahabad airport bamrauli air force station'),
 'along': ('ixv', 'along airport'),
 'amritsar': ('atq',
  'raja sansi international airport guru ram das airpor amritsar air force station'),
 'aurangabad': ('ixu', 'aurangabad airport chikkalthana airport'),
 'balurghat': ('rgh', 'balurghat airport'),
 'bangalore bengaluru': ('blr',
  'bengaluru international airport devanahalli airport'),
 'bathinda': ('bup', 'bhisiana air base bhatinda air force station'),
 'belgaum': ('ixg', 'belgaum airport'),
 'bellary': ('bep', 'bellary airport'),
 'bhavnagar': ('bhu', 'bhavnagar airport'),
 'bhopal': ('bho', 'bhopal airport raja bhoj airport'),
 'bhubaneswar': ('bbi', 'biju patnaik airport'),
 'bhuj': ('bhj',
  'bhuj airport shyamji krishna verma airport rudra mata air force base'),
 'bikaner': ('bkb', 'nal airport nal-bikaner air force station'),
 'bilaspur': ('pab', 'bilaspur airport'),
 'car nicobar': ('cbd', 'car nicobar air force base'),
 'chandigarh': ('ixc', 'chandigarh air force station'),
 'chennai madras': ('maa',
  'chennai international airport meenambakkam airport'),
 'coimbatore': ('cjb', 'coimbatore international airport'),
 'cooch behar': ('coh', 'cooch behar airport'),
 'cudappah': ('cdp', 'cuddapah airport'),
 'daman': ('nmb', 'daman airport'),
 'daporijo': ('dae', 'daporijo airport'),
 'dehradun': ('ded', 'jolly grant airport'),
 'delhi': ('del',
  'indira gandhi international airport palam air force station'),
 'dharamsala': ('dhm', 'gaggal airport'),
 'dibrugarh': ('dib', 'mohanbari air force station'),
 'dimapur': ('dmu', 'dimapur airport dimapur air base'),
 'diu': ('diu', 'diu airport'),
 'gandhinagar': ('amd',
  'sardar vallabhbhai patel international airport gandhinagar air force station'),
 'gaya': ('gay', 'gaya airport bodhgaya airport'),
 'goa': ('goi', 'dabolim airport dabolim naval air base'),
 'gorakhpur': ('gop', 'gorakhpur airport gorakhpur air force station'),
 'guwahati gauhati': ('gau',
  'lokpriya gopinath bordoloi international airport (borjhar airport) (mountain shadow air force station)'),
 'gwalior': ('gwl', 'gwalior airport maharajpur air force station'),
 'hubli': ('hbx', 'hubli airport hubli air base'),
 'hyderabad': ('hyd',
  'rajiv gandhi international airport hyderabad international airport'),
 'imphal': ('imf', 'imphal airport (tulihal airport)'),
 'indore': ('idr', 'devi ahilyabai holkar airport'),
 'jabalpur': ('jlr', 'jabalpur airport'),
 'jagdalpur': ('jgb', 'jagdalpur airport'),
 'jaipur': ('jai', 'jaipur airport sanganer airport'),
 'jaisalmer': ('jsa', 'jaisalmer airport jaisalmer air force station'),
 'jammu': ('ixj', 'jammu airport (satwari airport)'),
 'jamnagar': ('jga', 'jamnagar airport jamnagar air force station'),
 'jamshedpur': ('ixw', 'sonari airport'),
 'jaspur': ('pgh', 'jaspur trade airport'),
 'jodhpur': ('jdh', 'jodhpur airport jodhpur air force station'),
 'jorhat': ('jrh', 'jorhat air force station'),
 'kailashahar': ('ixh', 'kailashahar airport'),
 'kamalpur': ('ixq', 'kamalpur airport'),
 'kandla': ('ixy', 'kandla airport'),
 'kanpur': ('knu', 'kanpur civil airport'),
 'keshod': ('ixk', 'keshod airport'),
 'khajuraho': ('hjr', 'khajuraho airport'),
 'khowai': ('ixn', 'khowai airport'),
 'kochi cochin': ('cok', 'cochin international airport nedumbassery airport'),
 'kolhapur': ('klh', 'kolhapur airport'),
 'kolkata calcutta': ('ccu',
  'netaji subhash chandra bose international airport dum dum air force station'),
 'kota': ('ktu', 'kota airport'),
 'kozhikode (calicut)': ('ccj',
  'calicut international airport karipur airport'),
 'kulu': ('kuu', 'bhuntar airport'),
 'leh': ('ixl', 'leh kushok bakula rimpochee airport leh air base'),
 'lucknow': ('lko',
  'amausi airport chaudhary charan singh international airport'),
 'ludhiana': ('luh', 'sahnewal airport'),
 'madurai': ('ixm', 'madurai international airport madurai air force station'),
 'malda (english bazar)': ('lda', 'malda airport'),
 'mangalore': ('ixe', 'mangalore international airport bajpe airport'),
 'mumbai': ('bom',
  'chhatrapati shivaji international airport mumbai airport / bombay airport'),
 'muzzafarpur': ('mzu', 'muzzafarpur airport'),
 'mysore': ('myq', 'mandkalli airport'),
 'nagpur': ('nag',
  'dr. babasaheb ambedkar international airport nagpur air force station'),
 'nanded': ('ndc', 'nanded airport'),
 'nasik': ('isk', 'gandhinagar airport'),
 'north lakhimpur': ('ixi', 'lilabari airport'),
 'pantnagar': ('pgh', 'pantnagar airport'),
 'pasighat': ('ixt', 'pasighat airport'),
 'pathankot': ('ixp', 'pathankot airport pathankot air force station'),
 'patna': ('pat', 'lok nayak jayaprakash airport'),
 'pithoragarh': ('pgh', 'naini saini airport'),
 'pondicherry': ('pny', 'pondicherry airport'),
 'porbunder': ('pbd', 'porbandar airport'),
 'port blair': ('ixz', 'port blair air force station'),
 'pune poona': ('pnq',
  'pune international airport lohegaon air force station'),
 'purnea': ('pui', 'purnea airport'),
 'puttaparthi': ('bek', 'sri sathya sai airport'),
 'raipur': ('rpr', 'raipur airport mana airport'),
 'rajahmundry': ('rja', 'rajahmundry airport'),
 'rajkot': ('raj', 'rajkot airport'),
 'ranchi': ('ixr', 'birsa munda airport'),
 'ratnagiri': ('rtc', 'ratnagiri airport'),
 'rourkela': ('rrk', 'rourkela airport'),
 'rupsi': ('rup', 'rupsi airport'),
 'salem': ('sxv', 'salem airport'),
 'satna': ('tni', 'satna airport'),
 'shillong': ('shl',
  'shillong airport - umroi airport barapani air force station'),
 'shimla': ('slv', 'shimla airport'),
 'silchar': ('ixs', 'kumbhirgram air force station'),
 'siliguri': ('ixb', 'bagdogra air force station'),
 'solapur': ('sse', 'solapur airport'),
 'srinagar': ('sxr', 'srinagar air force station'),
 'surat': ('stv', 'surat airport'),
 'surendranagar': ('sun', 'zalawad airport'),
 'tezpur': ('tez', 'tezpur air force station'),
 'tezu': ('tei', 'tezu airport'),
 'thanjavur (tanjore)': ('tjv', 'thanjavur air force station (tanjore afs)'),
 'thiruvananthapuram (trivandrum)': ('trv',
  'trivandrum international airport trivandrum air force station'),
 'tiruchirapalli (trichy)': ('trz', 'tiruchirapalli international airport'),
 'tirupati': ('tir', 'tirupati airport'),
 'tuticorin': ('tcr', 'tuticorin airport'),
 'udaipur': ('udr', 'udaipur airport maharana pratap airport'),
 'vadodara (baroda)': ('bdq',
  'vadodara airport (harni airport) vadodara air base'),
 'varanasi (benares)': ('vns', 'varanasi airport babatpur airport'),
 'vijayawada': ('vga', 'vijayawada airport'),
 'visakhapatnam (vizag)': ('vtz',
  'visakhapatnam airport visakapatnam naval air base)'),
 'warangal': ('wgc', 'warangal airport'),
 'zero': ('zer', 'zero airport')}
